title: For Mole Problems, Call Avogadro
description: Opinions and facts about data science and machine learning
author: Oscar Cassetti

theme: jekyll-theme-minimal

future: true

plugins:
  - jekyll-sitemap
